/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#0b1324",
        "surface-container-low": "#141b2c",
        "surface-container": "#181f31",
        "surface-container-high": "#222a3c",
        "on-surface": "#dbe2fa",
        "on-surface-variant": "#c5c9ae",
        "slate-900": "#14171F",
        "slate-800": "#1E2330",
        "slate-700": "#262C3D",
        "slate-600": "#323A4D",
        "slate-500": "#4a5470",
        primary: "#feffec",
        "primary-fixed": "#c7f337",
        "primary-fixed-dim": "#acd60e",
        "on-primary-fixed": "#161e00",
        secondary: "#ffb59a",
        error: "#ffb4ab",
        "lime-glow": "rgba(198, 241, 53, 0.18)",
        "glass-bg": "rgba(30, 35, 48, 0.7)",
      },
      fontFamily: {
        "headline-lg": ["Fraunces", "serif"],
        "headline-md": ["Fraunces", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["IBM Plex Mono", "monospace"],
        "technical-sm": ["IBM Plex Mono", "monospace"],
        "code-block": ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["17px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["14.5px", { lineHeight: "1.75", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.5", letterSpacing: "0.14em", fontWeight: "500" }],
        "technical-sm": ["11px", { lineHeight: "1.4", fontWeight: "400" }],
        "code-block": ["13px", { lineHeight: "1.7", fontWeight: "400" }],
      },
      spacing: {
        "container-max": "720px",
        "section-gap": "48px",
        "component-gap": "20px",
        "element-gap-sm": "8px",
        "page-padding-top": "64px",
        "page-padding-x": "24px",
      },
      maxWidth: {
        "container-max": "720px",
      },
    },
  },
  plugins: [],
};
